import type { Metadata } from "next";
import Image from "next/image";
import { Breadcrumb, CTASection, Eyebrow, PageHero } from "@/components/site/Primitives";
import { ASSET_BASE } from "@/lib/site-data";

export const metadata: Metadata = { title: "Tecnologia", description: "Entenda a engenharia de conforto, controle térmico e durabilidade dos amortecedores BUMP.", alternates: { canonical: "/tecnologia" } };
const concepts = [{ title: "Corpo duplo", text: "Mais volume de fluido e proteção para manter o comportamento estável." }, { title: "Monotubo", text: "Pressão e resposta controladas para reduzir cavitação e perda de desempenho." }, { title: "Recuperável", text: "Construção desmontável para revisar o equipamento e ampliar sua vida útil." }] as const;
const comparison = [["Acerto", "Por veículo, carga e uso", "Configuração genérica"], ["Temperatura", "Maior controle térmico", "Perde resposta com uso severo"], ["Vida útil", "Desmontável e recuperável", "Frequentemente descartável"], ["Garantia", "2 anos contra vazamento", "Varia por produto"]] as const;

export default function TechnologyPage() { return <><Breadcrumb items={[{ label: "Home", href: "/" }, { label: "A BUMP" }, { label: "Tecnologia" }]} /><PageHero eyebrow="Engenharia do conforto" title="Corpo duplo. Tecnologia monotubo." description="Não é tecnologia para decorar ficha técnica. É para a picape amortecer do primeiro ao último quilômetro." />
<section className="section-space"><div className="site-container"><div className="relative min-h-[440px] overflow-hidden rounded-sm border border-line-2 bg-ink-frame"><Image src={`${ASSET_BASE}/amortecedoressemfundo/amortecedorpremiumsemfundo.webp`} alt="Diagrama visual de amortecedor BUMP" fill sizes="100vw" className="object-contain p-12" /></div><div className="mt-5 grid gap-4 md:grid-cols-3">{concepts.map((item) => <article key={item.title} className="surface-card p-7"><h2 className="text-xl font-black">{item.title}</h2><p className="mt-3 leading-relaxed text-mute-1">{item.text}</p></article>)}</div></div></section>
<section className="section-space border-y border-line-1 bg-ink-soft"><div className="site-container"><Eyebrow>BUMP versus amortecedor comum</Eyebrow><div className="mt-6 overflow-x-auto border border-line-2"><table className="w-full min-w-[650px] border-collapse text-left"><thead><tr className="bg-ink"><th className="p-4 font-mono text-xs text-mute-3">Critério</th><th className="p-4 font-mono text-xs text-accent">BUMP</th><th className="p-4 font-mono text-xs text-mute-3">Comum</th></tr></thead><tbody>{comparison.map((row) => <tr key={row[0]} className="border-t border-line-1"><th className="p-4 text-sm">{row[0]}</th><td className="p-4 text-sm font-semibold">{row[1]}</td><td className="p-4 text-sm text-mute-2">{row[2]}</td></tr>)}</tbody></table></div><div className="mt-10 grid gap-4 md:grid-cols-3">{[["Pressurizado", "Gás e fluido trabalham sob pressão controlada."], ["Curso", "Distância útil que a suspensão percorre."], ["Rebound", "Velocidade de retorno depois da compressão."]].map(([term, meaning]) => <div key={term} className="border-l-2 border-accent pl-5"><h3 className="font-bold">{term}</h3><p className="mt-2 text-sm text-mute-2">{meaning}</p></div>)}</div></div></section><CTASection title="Engenharia feita para o seu chão." /></>; }
